apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-nginx
  name: test-nginx #与Deployment同名
  namespace: test-namespace #指定namespace
spec:
  ports:
    - name: bdbdse #端口名称字符串
      nodePort: 32000 #物理机端口号
      port: 81 #服务端口
      protocol: TCP #端口协议,默认TCP
      targetPort: 81 #pod端口
  selector:
    app: test-nginx
  sessionAffinity: None #是否支持session
  type: NodePort

